name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.md'  # Déclenché si des fichiers Markdown sont modifiés
      - 'config.toml'  # Ou d'autres fichiers de configuration Hugo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Important pour les thèmes Hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify  # Minifie le HTML/CSS/JS

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Dossier de sortie de Hugo